"use strict";(self.webpackChunkmy_website=self.webpackChunkmy_website||[]).push([[1485],{7773:(r,e,a)=>{a.r(e),a.d(e,{assets:()=>u,contentTitle:()=>d,default:()=>R,frontMatter:()=>c,metadata:()=>p,toc:()=>v});var n=a(4848),t=a(8453),o=a(2364);const i='muro = UnwrapElement(IN[0])\r\n\r\n# utilizando el m\xe9todo LookupParameter()\r\nparamComent = muro.LookupParameter("Comentarios")\r\nparamLongi = muro.LookupParameter("Longitud")\r\nparamRestBase = muro.LookupParameter("Restricci\xf3n de base")\r\n\r\n# Obteniendo los valores del parameter\r\nval_ParmaCom = paramComent.AsString()\r\nval_paramLongi = paramLongi.AsDouble()\r\nval_paramRestBase = paramRestBase.AsElementId()\r\n\r\nval_paramLongi_2 = paramLongi.AsValueString()\r\n\r\nOUT = val_paramLongi, val_paramLongi_2',s='import clr\r\n\r\nclr.AddReference(\'RevitAPI\')\r\nfrom Autodesk.Revit.DB import BuiltInParameter\r\n\r\n\r\nmuro = UnwrapElement(IN[0])\r\n\r\n# utilizando el metodo LookupParameter()\r\n#paramComent = muro.LookupParameter("Comentarios")\r\nparamComent = muro.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)\r\n#paramLongi = muro.LookupParameter("Longitud")\r\nparamLongi = muro.get_Parameter(BuiltInParameter.CURVE_ELEM_LENGTH)\r\n#paramRestBase = muro.LookupParameter("Restricci\xf3n de base")\r\nparamRestBase = muro.get_Parameter(BuiltInParameter.WALL_BASE_CONSTRAINT)\r\n\r\n# Obteniendo los valores del parameter\r\nval_ParmaCom = paramComent.AsString()\r\nval_paramLongi = paramLongi.AsDouble()\r\nval_paramRestBase = paramRestBase.AsElementId()\r\n\r\nval_paramLongi_2 = paramLongi.AsValueString()\r\n\r\nOUT = val_paramLongi, val_paramLongi_2',m="\r\nimport clr\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitServices\")\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\n\r\nmuro = UnwrapElement(IN[0])\r\nnivel = UnwrapElement(IN[1])\r\n\r\nelementId_nivel = nivel.Id\r\n\r\n\r\n# Obtenemos el parametro Restriccion superior\r\nparamResSup = muro.get_Parameter(BuiltInParameter.WALL_HEIGHT_TYPE)\r\n\r\n\r\n# Inicializar la transaccion\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\n# Asiganrle un valor a este parametro\r\nresultado = paramResSup.Set(elementId_nivel)\r\n\r\n# Finalizar la transaccion\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\n\r\n\r\n# Asigne la salida a la variable OUT.\r\nOUT = resultado",l="\r\nimport clr\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitServices\")\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\n\r\nmuro = UnwrapElement(IN[0])\r\nnivel = UnwrapElement(IN[1])\r\n\r\nelementId_nivel = nivel.Id\r\n\r\n\r\n# Obtenemos el parametro Restriccion superior\r\nparamResSup = muro.get_Parameter(BuiltInParameter.WALL_HEIGHT_TYPE)\r\n\r\n\r\n# Inicializar la transaccion\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\n# Asiganrle un valor a este parametro\r\nresultado = paramResSup.Set(elementId_nivel)\r\n\r\n# Finalizar la transaccion\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\n\r\n\r\n# Asigne la salida a la variable OUT.\r\nOUT = resultado",c={sidebar_position:3},d="3. Par\xe1metros de Revit",p={id:"RevitAPI/03TrabajandoParametros",title:"3. Par\xe1metros de Revit",description:"3.1. Lectura de par\xe1metros de Elementos",source:"@site/docs/03-RevitAPI/03TrabajandoParametros.mdx",sourceDirName:"03-RevitAPI",slug:"/RevitAPI/03TrabajandoParametros",permalink:"/dynamoPythonGuia-OBG/docs/RevitAPI/03TrabajandoParametros",draft:!1,unlisted:!1,editUrl:"https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/docs/03-RevitAPI/03TrabajandoParametros.mdx",tags:[],version:"current",sidebarPosition:3,frontMatter:{sidebar_position:3},sidebar:"tutorialSidebar",previous:{title:"2. Objetos Dynamo Revit",permalink:"/dynamoPythonGuia-OBG/docs/RevitAPI/02ConversioNObjetosDynamoRevit"},next:{title:"4. Ejemplos Basicos",permalink:"/dynamoPythonGuia-OBG/docs/RevitAPI/04EjemplosBasicos"}},u={},v=[{value:"3.1. Lectura de par\xe1metros de Elementos",id:"31-lectura-de-par\xe1metros-de-elementos",level:2},{value:"3.2. Transacciones",id:"32-transacciones",level:2},{value:"3.3. Modificaci\xf3n de par\xe1metros",id:"33-modificaci\xf3n-de-par\xe1metros",level:2}];function g(r){const e={h1:"h1",h2:"h2",...(0,t.R)(),...r.components};return(0,n.jsxs)(n.Fragment,{children:[(0,n.jsx)(e.h1,{id:"3-par\xe1metros-de-revit",children:"3. Par\xe1metros de Revit"}),"\n",(0,n.jsx)(e.h2,{id:"31-lectura-de-par\xe1metros-de-elementos",children:"3.1. Lectura de par\xe1metros de Elementos"}),"\n",(0,n.jsx)(o.A,{language:"py",children:i}),"\n",(0,n.jsx)(o.A,{language:"py",children:s}),"\n",(0,n.jsx)(e.h2,{id:"32-transacciones",children:"3.2. Transacciones"}),"\n",(0,n.jsx)(e.h2,{id:"33-modificaci\xf3n-de-par\xe1metros",children:"3.3. Modificaci\xf3n de par\xe1metros"}),"\n",(0,n.jsx)(o.A,{language:"py",children:m}),"\n",(0,n.jsx)(o.A,{language:"py",children:l})]})}function R(r={}){const{wrapper:e}={...(0,t.R)(),...r.components};return e?(0,n.jsx)(e,{...r,children:(0,n.jsx)(g,{...r})}):g(r)}}}]);