---
sidebar_position: 1
---
# 1. Revit API

## 1.1. API (Application Programming Interface)

API significa "Interfaz de Programación de Aplicaciones" (Application Programming Interface en inglés). Es un conjunto de reglas, protocolos y herramientas que permiten a diferentes software interactuar entre sí. 

En términos simples, un API define cómo un software debe interactuar con otro, proporcionando una interfaz clara y bien definida para que los desarrolladores puedan utilizar las funciones y servicios ofrecidos por otro programa o plataforma.


## 1.2. ¿Como funciona la Revit API?
En contexto general podemos mencionar que existen principalmente dos Interfaces para interactuar con Revit:
* **API (Interfaz de Programación de Aplicaciones):** 
Diseñada para que los desarrolladores puedan interactuar con un programa de forma programática, (A traves de código) Por lo general, las APIs no proporcionan una interfaz visual directa para que los usuarios interactúen con el software

* **GUI (Interfaz Gráfica de Usuario):**
es una forma visual que permite a los usuarios interactuar con un programa mediante elementos gráficos como ventanas, botones, menús y otros controles. Están diseñadas para que los usuarios puedan interactuar de forma intuitiva con el software sin necesidad de conocer o escribir código.

<div style={{ textAlign: 'center' }}>
  <img
  src={require('./img/InterfacesRevit.png').default}
  alt="InterfacesRevit"/>
</div>

La Revit API es una interfaz de programación de aplicaciones (API, por sus siglas en inglés) proporcionada por Autodesk para  Autodesk Revit. 

:::info[]

La API de Revit permite a los desarrolladores crear scripts, complementos y aplicaciones personalizadas que pueden interactuar con los modelos de Revit y realizar una variedad de tareas automatizadas. Esto incluye la creación, modificación y eliminación de elementos del modelo, la generación de informes personalizados, el intercambio de datos con otros sistemas y la automatización de flujos de trabajo específicos.

:::

## 1.3. Enumeration Class

En `C#`, una enumeración (también conocida como `enum`) es un tipo de datos que permite definir un conjunto de constantes con nombre. Estas constantes representan valores discretos y específicos que son útiles cuando necesitas representar un conjunto fijo de opciones o estados en tu código.

En terminos simples podemos decir que una enum es una clase especail que no tiene metodos, no tiene propiedades y practicamente es una lisrta de objetos prestablecida.

Para usar una de las opciones de un enum se debe seguir la siguiente sintaxis:
```py
import clr

clr.AddReference([nombre_Biblioteca])
from [Namespace] import [nombre_Enum]


objetoEnum = [nombre_Enum].[nombre_Opcion]
```

donde :
* **`nombre_Biblioteca`:** Nombre la biblioteca a la cual pertenece el `enum`
* **`Namespace`:** Nombre del namespace del `enum`
* **`nombre_Enum`:** Nombre del `enum`
* **`nombre_Opcion`:** Nombre de la opción del `enum`

<details>
  <summary>**Ejemplo Enum `TaskDialogIcon`**</summary>

  En este ejemplo se muestra el uso del enum `TaskDialogIcon`, primero mostramos la documentación del mismo:

<div style={{ textAlign: 'center' }}>
  <img  style={{ maxWidth: '500px'}}
  src={require('./img/ejemploEnumTaskDialogIcon.png').default}
  alt="ejemploEnumTaskDialogIcon"/>
</div>

  Luego entonces usaríamos el enum de la siguiente manera:
```py
# Importación de bibliotecas
import clr

clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TaskDialogIcon

# Utilizando el icono de error del enum
objetoEnum = TaskDialogIcon.TaskDialogIconError
```
</details>

En la API de Revit, es muy comun encontrarnos con Enumerations, algunos ejemplos son:
* `BuiltInParameter`: Enumeration para el listado de identificadores de parametros de sistema
* `BuiltInCategory`: Enumeration para el listado de identificadores de categorias


## 1.4. Ejemplo Practico Clase TaskDialog
El siguiente ejemplo, muestra todo lo que hemos aprendido con relacion a las propiedades y metodos, usando la clase de Revit **TaskDialog**:

<details open>
  <summary>**Ejemplo TaskDialog**</summary>
  
  ```py
import clr

clr.AddReference('RevitAPIUI')
#from Autodesk.Revit.UI import TaskDialog, TaskDialogIcon, TaskDialogCommonButtons
from Autodesk.Revit.UI import *


# Puertos de entrada
titulo = IN[0]
contenido = IN[1]

# Instanciando un objeto TaskDialog
instanciaTaskDialog = TaskDialog("Este es un titulo inicial")

# Modificar la propiedad "Title", "MainInstruction", "MainContent", "FooterText"
instanciaTaskDialog.Title = titulo
instanciaTaskDialog.MainInstruction = "Este seria un contenido 1"
instanciaTaskDialog.MainContent = contenido
instanciaTaskDialog.FooterText = "Este es pie de pagina"

# Modificar la propiedad "EnableMarqueeProgressBar"
instanciaTaskDialog.EnableMarqueeProgressBar = True

# -----> Propiedades Enum <-----
# Modificar la propiedad "MainIcon" --> TaskDialogIcon (Enum)
instanciaTaskDialog.MainIcon = TaskDialogIcon.TaskDialogIconShield
# Modificar la propiedad "CommonButtons" --> TaskDialogCommonButtons (Enum)
instanciaTaskDialog.CommonButtons = TaskDialogCommonButtons.Ok

# Llamamos al método "Show()"
result = instanciaTaskDialog.Show()

# Devolvemos el resultado que es "TaskDialogResult"
OUT = result
  ```

</details>


## 1.5. Variables principales en Revit
Anteriormente mencionamos que dentro de Revit todo lo que encontremos es un objeto perteneciente a una determinada clase,
y en este contexto existe unos objetos comunes que estaremos usando a menudo, estos objetos pertenecen a las siguientes clases:

* **`UIApplication`** : Un objeto que representa una sesión activa de la interfaz de usuario de Autodesk Revit, proporcionando acceso a métodos de personalización de la interfaz de usuario, eventos, la ventana principal y el documento activo.
* **`Application`** : Un objeto que representa la aplicación Autodesk Revit, proporcionando acceso a documentos, opciones y otros datos y configuraciones de la aplicación en toda la aplicación.
* **`UIDocument`** : Un objeto que representa un proyecto de Autodesk Revit abierto en la interfaz de usuario de Revit.
* **`Document`** : Un objeto que representa un proyecto de Revit abierto.


```python
import clr

clr.AddReference("RevitServices")
from RevitServices.Persistence import DocumentManager

# Principales variables que tal vez usemos
uiapp = DocumentManager.Instance.CurrentUIApplication #---> UIApplication
app = uiapp.Application #---> Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument #---> UIDocument
doc = DocumentManager.Instance.CurrentDBDocument #---> Document
```

<details close>
  <summary>**Ejemplo: Obtener Version de Revit**</summary>

  En este ejemplo se muestra como obetenr la version de Revit que se esta ejecutando
```python
uiapp = DocumentManager.Instance.CurrentUIApplication #---> UIApplication
app = uiapp.Application #---> Application
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument #---> UIDocument
doc = DocumentManager.Instance.CurrentDBDocument #---> Document

# Gets revit version number
# resaltado--next-line
rvtVersion = app.VersionNumber

# Titulo del proyecto
# resaltado--next-line
titulo = doc.Title

# Accediendo a la vista activa
# resaltado--next-line
vistaActiva = doc.ActiveView

OUT = rvtVersion
```

  {/* <CodeBlock language="py">{ej_textNoteMayuscula}</CodeBlock> */}
</details>

<details close>
  <summary>**Ejemplo: Obtener un elemento**</summary>

  En este ejemplo se muestra como obetenr un elemento a partir del numero de Id
```python
doc = DocumentManager.Instance.CurrentDBDocument 

int_id = IN[0]
id = ElementId(int_id) # ElementId

# Obtener un elemento 
# resaltado--next-line
elemento = doc.GetElement(id)

OUT = elemento
```

  {/* <CodeBlock language="py">{ej_textNoteMayuscula}</CodeBlock> */}
</details>

## 1.7. Uso de RevitLookup


## 1.8. Plantilla .py para un Python Script

En nuestros Python Scripts la mayoría de veces tendremos código repetitivo, por lo que conviene tener una plantilla con este código repetitivo, de forma tal que cuando editemos nuestro nodo Python Script, podamos borrar lo que no necesitemos y quedarnos con lo que si.
Dynamo permite realizar estas configuraciones para ello podemos ingresar al [Dyanmo Primer](https://primer.dynamobim.org/10_Custom-Nodes/10-6_Python-Templates.html) para obtener mayor información.

Aqui te dejamos una plantilla que normalmente utilizamos:

```py
import sys
import clr
import math

clr.AddReference('System')
from System.Collections.Generic import List

# Import Geometry dynamo
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
from Autodesk.DesignScript.Geometry import Curve as CurvaDynamo

# import DCCoreNodes
clr.AddReference('DSCoreNodes')
import DSCore
from DSCore import *

# Import Revit API
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Curve as CurvaRevit
from Autodesk.Revit.DB.Architecture import *
from Autodesk.Revit.DB.Structure import *

# Import Revit APIUI
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

# import Revit Nodes and extensions
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

"""
#Conversiones de Objetos de Revit a Dynamo y Viceversa
#---------Revit a Dynamo
#Elements
Element.ToDSType(bool); #true if it's an element generated by Revit
#Geometry
XYZ.ToPoint() > Point
XYZ.ToVector() > Vector
Point.ToProtoType() > Point
List<XYZ>.ToPoints() > List<Point>
UV.ToProtoType() > UV
Curve.ToProtoType() > Curve
CurveArray.ToProtoType() > PolyCurve
PolyLine.ToProtoType() > PolyCurve
Plane.ToPlane() > Plane
Solid.ToProtoType() > Solid
Mesh.ToProtoType() > Mesh
IEnumerable<Mesh>.ToProtoType() > Mesh[]
Face.ToProtoType() > IEnumerable<Surface>
Transform.ToCoordinateSystem() > CoordinateSystem
BoundingBoxXYZ.ToProtoType() > BoundingBox

#---------Dynamo a Revit
#Elements
Element.InternalElement
#Geometry
Point.ToRevitType() > XYZ
Vector.ToRevitType() > XYZ
Plane.ToPlane() > Plane
List<Point>.ToXyzs() > List<XYZ>
Curve.ToRevitType() > Curve
PolyCurve.ToRevitType() > CurveLoop
Surface.ToRevitType() > IList<GeometryObject>
Solid.ToRevitType() > IList<GeometryObject>
Mesh.ToRevitType() > IList<GeometryObject>
CoordinateSystem.ToTransform() > Transform
CoordinateSystem.ToRevitBoundingBox() > BoundingBoxXYZ
BoundingBox.ToRevitType() > BoundingBoxXYZ
"""


# Import Document Manager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Principales variables que tal vez usemos
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

# Utilización de Transacciones
TransactionManager.Instance.EnsureInTransaction(doc)

TransactionManager.Instance.TransactionTaskDone()

OUT = 0
```